"""
core/_orphan_integration.py — Phase 25: Orphan Module Wire-Up
=============================================================

Wires every previously-orphaned production module into the runtime
ServiceRegistry, so they're discoverable by other modules and
accessible via `runtime.get("<name>")`.

Each module is wrapped in its own try/except — a broken import or
constructor logs a WARNING but does NOT fail the phase or break boot.
This is intentional: the wired modules are *additive* enhancements
(risk guardrails, monitoring, analysis engines); the system already
runs without them. Making them hard dependencies would regress
availability.

Total modules attempted: 83

Generated by `scripts/build_orphan_integration.py`. Re-run that
script after adding new entries to MODULES list above.
"""

from __future__ import annotations

import logging
from typing import Any, List, Tuple

from core.event_bus import get_bus
from core.lifecycle import Phase, PhaseResult
from core.service_registry import ServiceRegistry

log = logging.getLogger(__name__)

# Track which wired modules asked for event-bus subscriptions, so
# boot_orphan_integration() can wire them up after registration.
_SUBSCRIBED: dict[str, str] = {}


def boot_orphan_integration(registry: ServiceRegistry) -> PhaseResult:
    """Phase 25 — Wire previously-orphaned production modules.

    Each module is registered independently; failures are isolated.
    Returns ``ok=True`` always (this phase is non-critical).
    """
    _wired: List[str] = []
    _failed: List[Tuple[str, str]] = []

    # Pull frequently-used config constants up front (lazy import so
    # config validation errors don't crash this phase — they'll be
    # caught by the per-module try/except below).
    try:
        from config import (
            INITIAL_BALANCE, MAX_LOT, RISK_PER_TRADE, APPROVAL_MODE,
        )
    except Exception:
        INITIAL_BALANCE = 10000.0
        MAX_LOT = 0.5
        RISK_PER_TRADE = 0.005
        APPROVAL_MODE = "auto"

    log.info("=" * 60)
    log.info("Phase 25 — Orphan Module Integration (wiring %d modules)",
             83)
    log.info("=" * 60)

    # Thin orchestrator over Kelly + correlation + drawdown
    try:
        from risk.advanced_risk_orchestrator import AdvancedRiskOrchestrator as _AdvancedRiskOrchestrator
        try:
            _service = _AdvancedRiskOrchestrator(account_balance=INITIAL_BALANCE, max_lot_size=MAX_LOT, risk_per_trade_pct=RISK_PER_TRADE)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("advanced_risk_orchestrator")(df, ...)`.
            _service = _AdvancedRiskOrchestrator
        registry.register_instance("advanced_risk_orchestrator", _service)
        _wired.append("advanced_risk_orchestrator")
        log.info("  ✓ advanced_risk_orchestrator")
        _SUBSCRIBED["advanced_risk_orchestrator"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("advanced_risk_orchestrator", str(_e)))
        log.warning("  ✗ advanced_risk_orchestrator: %s", _e)

    # RED_TEAM_REPORT defenses (instantiated as the guard class)
    try:
        from risk.adversarial_defenses import BrokerExecutionGuard as _BrokerExecutionGuard
        try:
            _service = _BrokerExecutionGuard()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("adversarial_defenses")(df, ...)`.
            _service = _BrokerExecutionGuard
        registry.register_instance("adversarial_defenses", _service)
        _wired.append("adversarial_defenses")
        log.info("  ✓ adversarial_defenses")
        _SUBSCRIBED["adversarial_defenses"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("adversarial_defenses", str(_e)))
        log.warning("  ✗ adversarial_defenses: %s", _e)

    # Volume-weighted basket exit for grid-scaled positions
    try:
        from risk.basket_exit import BasketExitManager as _BasketExitManager
        try:
            _service = _BasketExitManager(tp_pips=30, sl_pips=50, pip_size=0.0001)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("basket_exit_manager")(df, ...)`.
            _service = _BasketExitManager
        registry.register_instance("basket_exit_manager", _service)
        _wired.append("basket_exit_manager")
        log.info("  ✓ basket_exit_manager")
        _SUBSCRIBED["basket_exit_manager"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("basket_exit_manager", str(_e)))
        log.warning("  ✗ basket_exit_manager: %s", _e)

    # Book P136-151 guardrails (module-level fns: check_correlation_exposure, check_anti_revenge, check_net_ev) (registered as module/class — callers invoke directly)
    try:
        from risk.book_guardrails import check_correlation_exposure as _check_correlation_exposure
        registry.register_instance("book_guardrails", _check_correlation_exposure)
        _wired.append("book_guardrails")
        log.info("  ✓ book_guardrails (as module)")
        _SUBSCRIBED["book_guardrails"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("book_guardrails", str(_e)))
        log.warning("  ✗ book_guardrails: %s", _e)

    # Persisted lot-multiplier engine
    try:
        from risk.compounding import CompoundingEngine as _CompoundingEngine
        try:
            _service = _CompoundingEngine(initial_balance=INITIAL_BALANCE)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("compounding_engine")(df, ...)`.
            _service = _CompoundingEngine
        registry.register_instance("compounding_engine", _service)
        _wired.append("compounding_engine")
        log.info("  ✓ compounding_engine")
        _SUBSCRIBED["compounding_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("compounding_engine", str(_e)))
        log.warning("  ✗ compounding_engine: %s", _e)

    # Non-martingale grid scaling
    try:
        from risk.controlled_grid_scaler import ControlledGridScaler as _ControlledGridScaler
        try:
            _service = _ControlledGridScaler(max_levels=3, lot_size=0.1, lot_multiplier=1.0, min_spacing_pips=20, pip_size=0.0001, max_basket_loss_usd=100.0)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("controlled_grid_scaler")(df, ...)`.
            _service = _ControlledGridScaler
        registry.register_instance("controlled_grid_scaler", _service)
        _wired.append("controlled_grid_scaler")
        log.info("  ✓ controlled_grid_scaler")
        _SUBSCRIBED["controlled_grid_scaler"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("controlled_grid_scaler", str(_e)))
        log.warning("  ✗ controlled_grid_scaler: %s", _e)

    # Anti-chasing filters (6 red-flag checks via module-level fns) (registered as module/class — callers invoke directly)
    try:
        from risk.entry_quality_guardrails import check_chasing_filter as _check_chasing_filter
        registry.register_instance("entry_quality_guardrails", _check_chasing_filter)
        _wired.append("entry_quality_guardrails")
        log.info("  ✓ entry_quality_guardrails (as module)")
        _SUBSCRIBED["entry_quality_guardrails"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("entry_quality_guardrails", str(_e)))
        log.warning("  ✗ entry_quality_guardrails: %s", _e)

    # System-health evaluator with confidence intervals
    try:
        from risk.expectancy import ExpectancyCalculator as _ExpectancyCalculator
        try:
            _service = _ExpectancyCalculator()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("expectancy_calculator")(df, ...)`.
            _service = _ExpectancyCalculator
        registry.register_instance("expectancy_calculator", _service)
        _wired.append("expectancy_calculator")
        log.info("  ✓ expectancy_calculator")
        _SUBSCRIBED["expectancy_calculator"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("expectancy_calculator", str(_e)))
        log.warning("  ✗ expectancy_calculator: %s", _e)

    # 200-point entry framework with 14 dimensions
    try:
        from risk.institutional_entry_framework import evaluate_institutional_entry as _evaluate_institutional_entry
        try:
            _service = _evaluate_institutional_entry()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("institutional_entry_framework")(df, ...)`.
            _service = _evaluate_institutional_entry
        registry.register_instance("institutional_entry_framework", _service)
        _wired.append("institutional_entry_framework")
        log.info("  ✓ institutional_entry_framework")
        _SUBSCRIBED["institutional_entry_framework"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("institutional_entry_framework", str(_e)))
        log.warning("  ✗ institutional_entry_framework: %s", _e)

    # Risk-of-ruin simulator
    try:
        from risk.monte_carlo import MonteCarloEngine as _MonteCarloEngine
        try:
            _service = _MonteCarloEngine(seed=42)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("monte_carlo_engine")(df, ...)`.
            _service = _MonteCarloEngine
        registry.register_instance("monte_carlo_engine", _service)
        _wired.append("monte_carlo_engine")
        log.info("  ✓ monte_carlo_engine")
        _SUBSCRIBED["monte_carlo_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("monte_carlo_engine", str(_e)))
        log.warning("  ✗ monte_carlo_engine: %s", _e)

    # Order-split + TP2 trailing-stop manager
    try:
        from risk.order_split_manager import OrderSplitManager as _OrderSplitManager
        try:
            _service = _OrderSplitManager()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("order_split_manager")(df, ...)`.
            _service = _OrderSplitManager
        registry.register_instance("order_split_manager", _service)
        _wired.append("order_split_manager")
        log.info("  ✓ order_split_manager")
        _SUBSCRIBED["order_split_manager"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("order_split_manager", str(_e)))
        log.warning("  ✗ order_split_manager: %s", _e)

    # Kelly-Criterion position sizer
    try:
        from risk.position_allocator import PositionAllocator as _PositionAllocator
        try:
            _service = _PositionAllocator(balance=INITIAL_BALANCE, kelly_fraction=0.5, min_rr=2.0)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("position_allocator")(df, ...)`.
            _service = _PositionAllocator
        registry.register_instance("position_allocator", _service)
        _wired.append("position_allocator")
        log.info("  ✓ position_allocator")
        _SUBSCRIBED["position_allocator"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("position_allocator", str(_e)))
        log.warning("  ✗ position_allocator: %s", _e)

    # EV calculation with outcome distribution (module-level fn exposed as service) (registered as module/class — callers invoke directly)
    try:
        from risk.probability_distribution import compute_outcome_probabilities as _compute_outcome_probabilities
        registry.register_instance("probability_distribution", _compute_outcome_probabilities)
        _wired.append("probability_distribution")
        log.info("  ✓ probability_distribution (as module)")
        _SUBSCRIBED["probability_distribution"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("probability_distribution", str(_e)))
        log.warning("  ✗ probability_distribution: %s", _e)

    # Minimum RR policy (already used transitively, now formalized)
    try:
        from risk.rr_policy import get_min_rr as _get_min_rr
        try:
            _service = _get_min_rr()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("rr_policy")(df, ...)`.
            _service = _get_min_rr
        registry.register_instance("rr_policy", _service)
        _wired.append("rr_policy")
        log.info("  ✓ rr_policy")
        _SUBSCRIBED["rr_policy"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("rr_policy", str(_e)))
        log.warning("  ✗ rr_policy: %s", _e)

    # Consolidated consecutive-loss streak counter
    try:
        from risk.streak_tracker import StreakTracker as _StreakTracker
        try:
            _service = _StreakTracker()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("streak_tracker")(df, ...)`.
            _service = _StreakTracker
        registry.register_instance("streak_tracker", _service)
        _wired.append("streak_tracker")
        log.info("  ✓ streak_tracker")
        _SUBSCRIBED["streak_tracker"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("streak_tracker", str(_e)))
        log.warning("  ✗ streak_tracker: %s", _e)

    # Structure-based stop-loss computation (module-level fn) (registered as module/class — callers invoke directly)
    try:
        from risk.structure_stop import compute_structure_stop as _compute_structure_stop
        registry.register_instance("structure_stop", _compute_structure_stop)
        _wired.append("structure_stop")
        log.info("  ✓ structure_stop (as module)")
        _SUBSCRIBED["structure_stop"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("structure_stop", str(_e)))
        log.warning("  ✗ structure_stop: %s", _e)

    # One-direction-per-symbol guard
    try:
        from risk.symbol_lock import SymbolLock as _SymbolLock
        try:
            _service = _SymbolLock(max_positions_per_symbol=1)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("symbol_lock")(df, ...)`.
            _service = _SymbolLock
        registry.register_instance("symbol_lock", _service)
        _wired.append("symbol_lock")
        log.info("  ✓ symbol_lock")
        _SUBSCRIBED["symbol_lock"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("symbol_lock", str(_e)))
        log.warning("  ✗ symbol_lock: %s", _e)

    # Min/max daily trades enforcement
    try:
        from risk.trade_frequency import TradeFrequencyController as _TradeFrequencyController
        try:
            _service = _TradeFrequencyController()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("trade_frequency_controller")(df, ...)`.
            _service = _TradeFrequencyController
        registry.register_instance("trade_frequency_controller", _service)
        _wired.append("trade_frequency_controller")
        log.info("  ✓ trade_frequency_controller")
        _SUBSCRIBED["trade_frequency_controller"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("trade_frequency_controller", str(_e)))
        log.warning("  ✗ trade_frequency_controller: %s", _e)

    # Pre-trade guard-rails container (MaxOrderCount/Size/Position)
    try:
        from risk.trading_controls import TradingControls as _TradingControls
        try:
            _service = _TradingControls()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("trading_controls")(df, ...)`.
            _service = _TradingControls
        registry.register_instance("trading_controls", _service)
        _wired.append("trading_controls")
        log.info("  ✓ trading_controls")
        _SUBSCRIBED["trading_controls"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("trading_controls", str(_e)))
        log.warning("  ✗ trading_controls: %s", _e)

    # Stop-sequencing logic for breakout strategies (module-level fn) (registered as module/class — callers invoke directly)
    try:
        from risk.channel_breakout_stops import select_active_stop as _select_active_stop
        registry.register_instance("channel_breakout_stops", _select_active_stop)
        _wired.append("channel_breakout_stops")
        log.info("  ✓ channel_breakout_stops (as module)")
        _SUBSCRIBED["channel_breakout_stops"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("channel_breakout_stops", str(_e)))
        log.warning("  ✗ channel_breakout_stops: %s", _e)

    # 3-mode supervision layer; persists pending approvals across restarts
    try:
        from core.approval_mode import ApprovalMode as _ApprovalMode
        try:
            _service = _ApprovalMode(mode=2)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("approval_mode")(df, ...)`.
            _service = _ApprovalMode
        registry.register_instance("approval_mode", _service)
        _wired.append("approval_mode")
        log.info("  ✓ approval_mode")
        _SUBSCRIBED["approval_mode"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("approval_mode", str(_e)))
        log.warning("  ✗ approval_mode: %s", _e)

    # JSONL audit-report generator
    try:
        from core.audit_report import DecisionAuditReport as _DecisionAuditReport
        try:
            _service = _DecisionAuditReport()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("audit_report")(df, ...)`.
            _service = _DecisionAuditReport
        registry.register_instance("audit_report", _service)
        _wired.append("audit_report")
        log.info("  ✓ audit_report")
        _SUBSCRIBED["audit_report"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("audit_report", str(_e)))
        log.warning("  ✗ audit_report: %s", _e)

    # SQLite-backed dynamic weight adjustment across intelligence layers
    try:
        from core.confidence_manager import ConfidenceManager as _ConfidenceManager
        try:
            _service = _ConfidenceManager()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("confidence_manager")(df, ...)`.
            _service = _ConfidenceManager
        registry.register_instance("confidence_manager", _service)
        _wired.append("confidence_manager")
        log.info("  ✓ confidence_manager")
        _SUBSCRIBED["confidence_manager"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("confidence_manager", str(_e)))
        log.warning("  ✗ confidence_manager: %s", _e)

    # Execution-parity data provider (Live MT5)
    try:
        from core.data_provider import LiveMT5Provider as _LiveMT5Provider
        try:
            _service = _LiveMT5Provider(market_agent=None)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("data_provider_live")(df, ...)`.
            _service = _LiveMT5Provider
        registry.register_instance("data_provider_live", _service)
        _wired.append("data_provider_live")
        log.info("  ✓ data_provider_live")
        _SUBSCRIBED["data_provider_live"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("data_provider_live", str(_e)))
        log.warning("  ✗ data_provider_live: %s", _e)

    # Final decision gate with Ollama veto (fail-open)
    try:
        from core.decision_validator import DecisionValidator as _DecisionValidator
        try:
            _service = _DecisionValidator()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("decision_validator")(df, ...)`.
            _service = _DecisionValidator
        registry.register_instance("decision_validator", _service)
        _wired.append("decision_validator")
        log.info("  ✓ decision_validator")
        _SUBSCRIBED["decision_validator"] = "system.decision.validated"  # empty = no subscription
    except Exception as _e:
        _failed.append(("decision_validator", str(_e)))
        log.warning("  ✗ decision_validator: %s", _e)

    # Execution-parity MT5 adapter (ABC; concrete adapters take router/broker)
    try:
        from core.execution_adapter import ExecutionAdapter as _ExecutionAdapter
        try:
            _service = _ExecutionAdapter()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("execution_adapter_mt5")(df, ...)`.
            _service = _ExecutionAdapter
        registry.register_instance("execution_adapter_mt5", _service)
        _wired.append("execution_adapter_mt5")
        log.info("  ✓ execution_adapter_mt5")
        _SUBSCRIBED["execution_adapter_mt5"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("execution_adapter_mt5", str(_e)))
        log.warning("  ✗ execution_adapter_mt5: %s", _e)

    # TTL+LRU indicator cache (also exports singleton `global_indicator_cache`)
    try:
        from core.indicator_cache import IndicatorCache as _IndicatorCache
        try:
            _service = _IndicatorCache(max_size=500, ttl_seconds=300)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("indicator_cache")(df, ...)`.
            _service = _IndicatorCache
        registry.register_instance("indicator_cache", _service)
        _wired.append("indicator_cache")
        log.info("  ✓ indicator_cache")
        _SUBSCRIBED["indicator_cache"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("indicator_cache", str(_e)))
        log.warning("  ✗ indicator_cache: %s", _e)

    # 3-in-1 production utilities (pair selector + sizer + journal)
    try:
        from core.professional_tools import DynamicPositionSizer as _DynamicPositionSizer
        try:
            _service = _DynamicPositionSizer()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("professional_tools")(df, ...)`.
            _service = _DynamicPositionSizer
        registry.register_instance("professional_tools", _service)
        _wired.append("professional_tools")
        log.info("  ✓ professional_tools")
        _SUBSCRIBED["professional_tools"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("professional_tools", str(_e)))
        log.warning("  ✗ professional_tools: %s", _e)

    # Book P15 false-signal regime suppression
    try:
        from core.regime_suppression import RegimeSuppressor as _RegimeSuppressor
        try:
            _service = _RegimeSuppressor()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("regime_suppressor")(df, ...)`.
            _service = _RegimeSuppressor
        registry.register_instance("regime_suppressor", _service)
        _wired.append("regime_suppressor")
        log.info("  ✓ regime_suppressor")
        _SUBSCRIBED["regime_suppressor"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("regime_suppressor", str(_e)))
        log.warning("  ✗ regime_suppressor: %s", _e)

    # Book P15 anti-flip-flop filter
    try:
        from core.signal_persistence import SignalPersistenceFilter as _SignalPersistenceFilter
        try:
            _service = _SignalPersistenceFilter()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("signal_persistence_filter")(df, ...)`.
            _service = _SignalPersistenceFilter
        registry.register_instance("signal_persistence_filter", _service)
        _wired.append("signal_persistence_filter")
        log.info("  ✓ signal_persistence_filter")
        _SUBSCRIBED["signal_persistence_filter"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("signal_persistence_filter", str(_e)))
        log.warning("  ✗ signal_persistence_filter: %s", _e)

    # Cumulative score-based decision — explicitly built to fix '0 trades in 24h' bug
    try:
        from core.signal_scorer import SignalScorer as _SignalScorer
        try:
            _service = _SignalScorer()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("signal_scorer")(df, ...)`.
            _service = _SignalScorer
        registry.register_instance("signal_scorer", _service)
        _wired.append("signal_scorer")
        log.info("  ✓ signal_scorer")
        _SUBSCRIBED["signal_scorer"] = "system.signal.scored"  # empty = no subscription
    except Exception as _e:
        _failed.append(("signal_scorer", str(_e)))
        log.warning("  ✗ signal_scorer: %s", _e)

    # Canonical signal schema (dataclass; producing agents migrate gradually) (registered as module/class — callers invoke directly)
    try:
        from core.unified_signal import UnifiedSignal as _UnifiedSignal
        registry.register_instance("unified_signal_schema", _UnifiedSignal)
        _wired.append("unified_signal_schema")
        log.info("  ✓ unified_signal_schema (as module)")
        _SUBSCRIBED["unified_signal_schema"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("unified_signal_schema", str(_e)))
        log.warning("  ✗ unified_signal_schema: %s", _e)

    # Soft confluence scoring, replaces all-or-nothing gate
    try:
        from analysis.adaptive_decision_engine import AdaptiveDecisionEngine as _AdaptiveDecisionEngine
        try:
            _service = _AdaptiveDecisionEngine(mode='conservative')  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("adaptive_decision_engine")(df, ...)`.
            _service = _AdaptiveDecisionEngine
        registry.register_instance("adaptive_decision_engine", _service)
        _wired.append("adaptive_decision_engine")
        log.info("  ✓ adaptive_decision_engine")
        _SUBSCRIBED["adaptive_decision_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("adaptive_decision_engine", str(_e)))
        log.warning("  ✗ adaptive_decision_engine: %s", _e)

    # ADX day-over-day rising filter + Bishop exit (module-level fns) (registered as module/class — callers invoke directly)
    try:
        from analysis.adx_filters import adx_rising as _adx_rising
        registry.register_instance("adx_filters", _adx_rising)
        _wired.append("adx_filters")
        log.info("  ✓ adx_filters (as module)")
        _SUBSCRIBED["adx_filters"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("adx_filters", str(_e)))
        log.warning("  ✗ adx_filters: %s", _e)

    # Standard ADX filter (requires `ta` lib)
    try:
        from analysis.adx_trend_filter import compute as _compute
        try:
            _service = _compute()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("adx_trend_filter")(df, ...)`.
            _service = _compute
        registry.register_instance("adx_trend_filter", _service)
        _wired.append("adx_trend_filter")
        log.info("  ✓ adx_trend_filter")
        _SUBSCRIBED["adx_trend_filter"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("adx_trend_filter", str(_e)))
        log.warning("  ✗ adx_trend_filter: %s", _e)

    # Elliott Wave + EMA Ribbon + Fake Breakout + Wyckoff (module-level fns) (registered as module/class — callers invoke directly)
    try:
        from analysis.advanced_filters import detect_elliott_wave as _detect_elliott_wave
        registry.register_instance("advanced_filters", _detect_elliott_wave)
        _wired.append("advanced_filters")
        log.info("  ✓ advanced_filters (as module)")
        _SUBSCRIBED["advanced_filters"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("advanced_filters", str(_e)))
        log.warning("  ✗ advanced_filters: %s", _e)

    # Glue between UnifiedSignalEngine and AdaptiveDecisionEngine
    try:
        from analysis.decision_bridge import UnifiedToAdaptiveBridge as _UnifiedToAdaptiveBridge
        try:
            _service = _UnifiedToAdaptiveBridge(weights_path=None)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("decision_bridge")(df, ...)`.
            _service = _UnifiedToAdaptiveBridge
        registry.register_instance("decision_bridge", _service)
        _wired.append("decision_bridge")
        log.info("  ✓ decision_bridge")
        _SUBSCRIBED["decision_bridge"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("decision_bridge", str(_e)))
        log.warning("  ✗ decision_bridge: %s", _e)

    # Nison 3-criteria + confluence engulfing detector
    try:
        from analysis.engulfing_bar_strategy import EngulfingBarStrategy as _EngulfingBarStrategy
        try:
            _service = _EngulfingBarStrategy(timeframe='H4')  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("engulfing_bar_strategy")(df, ...)`.
            _service = _EngulfingBarStrategy
        registry.register_instance("engulfing_bar_strategy", _service)
        _wired.append("engulfing_bar_strategy")
        log.info("  ✓ engulfing_bar_strategy")
        _SUBSCRIBED["engulfing_bar_strategy"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("engulfing_bar_strategy", str(_e)))
        log.warning("  ✗ engulfing_bar_strategy: %s", _e)

    # Cross-cutting rule-spec filters (doji density, gap-for-stars)
    try:
        from analysis.global_filters import doji_density as _doji_density
        try:
            _service = _doji_density()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("global_filters")(df, ...)`.
            _service = _doji_density
        registry.register_instance("global_filters", _service)
        _wired.append("global_filters")
        log.info("  ✓ global_filters")
        _SUBSCRIBED["global_filters"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("global_filters", str(_e)))
        log.warning("  ✗ global_filters: %s", _e)

    # Strict spec-compliant candlestick library (20 patterns)
    try:
        from analysis.high_reliability_patterns import DetectedPattern as _DetectedPattern
        try:
            _service = _DetectedPattern()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("high_reliability_patterns")(df, ...)`.
            _service = _DetectedPattern
        registry.register_instance("high_reliability_patterns", _service)
        _wired.append("high_reliability_patterns")
        log.info("  ✓ high_reliability_patterns")
        _SUBSCRIBED["high_reliability_patterns"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("high_reliability_patterns", str(_e)))
        log.warning("  ✗ high_reliability_patterns: %s", _e)

    # 6-step ICT/SMC AMD+FVG+MSS signal engine (class)
    try:
        from analysis.ict_amd_signal_engine import ICTAMDSignalEngine as _ICTAMDSignalEngine
        try:
            _service = _ICTAMDSignalEngine()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ict_amd_signal_engine")(df, ...)`.
            _service = _ICTAMDSignalEngine
        registry.register_instance("ict_amd_signal_engine", _service)
        _wired.append("ict_amd_signal_engine")
        log.info("  ✓ ict_amd_signal_engine")
        _SUBSCRIBED["ict_amd_signal_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ict_amd_signal_engine", str(_e)))
        log.warning("  ✗ ict_amd_signal_engine: %s", _e)

    # Composes liquidity_zones + session_analysis + stop_hunt_detector
    try:
        from analysis.liquidity_engine import LiquidityEngine as _LiquidityEngine
        try:
            _service = _LiquidityEngine()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("liquidity_engine")(df, ...)`.
            _service = _LiquidityEngine
        registry.register_instance("liquidity_engine", _service)
        _wired.append("liquidity_engine")
        log.info("  ✓ liquidity_engine")
        _SUBSCRIBED["liquidity_engine"] = "analysis.liquidity.ready"  # empty = no subscription
    except Exception as _e:
        _failed.append(("liquidity_engine", str(_e)))
        log.warning("  ✗ liquidity_engine: %s", _e)

    # Equal H/L + PDH/PDL/PWH/PWL + Asian range
    try:
        from analysis.liquidity_zones import LiquidityZoneMapper as _LiquidityZoneMapper
        try:
            _service = _LiquidityZoneMapper()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("liquidity_zones")(df, ...)`.
            _service = _LiquidityZoneMapper
        registry.register_instance("liquidity_zones", _service)
        _wired.append("liquidity_zones")
        log.info("  ✓ liquidity_zones")
        _SUBSCRIBED["liquidity_zones"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("liquidity_zones", str(_e)))
        log.warning("  ✗ liquidity_zones: %s", _e)

    # Rolling memory of recent market behavior, persisted
    try:
        from analysis.market_state_memory import MarketStateMemory as _MarketStateMemory
        try:
            _service = _MarketStateMemory()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("market_state_memory")(df, ...)`.
            _service = _MarketStateMemory
        registry.register_instance("market_state_memory", _service)
        _wired.append("market_state_memory")
        log.info("  ✓ market_state_memory")
        _SUBSCRIBED["market_state_memory"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("market_state_memory", str(_e)))
        log.warning("  ✗ market_state_memory: %s", _e)

    # Stateless megaphone/pennant formation classifier
    try:
        from analysis.megaphone_pennant import classify as _classify
        try:
            _service = _classify()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("megaphone_pennant_classifier")(df, ...)`.
            _service = _classify
        registry.register_instance("megaphone_pennant_classifier", _service)
        _wired.append("megaphone_pennant_classifier")
        log.info("  ✓ megaphone_pennant_classifier")
        _SUBSCRIBED["megaphone_pennant_classifier"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("megaphone_pennant_classifier", str(_e)))
        log.warning("  ✗ megaphone_pennant_classifier: %s", _e)

    # 4-TF top-down (H4→H1→M15→M5)
    try:
        from analysis.mtf_analyzer import MTFAnalyzer as _MTFAnalyzer
        try:
            # NOTE (2026-08-25 log-audit): 'EURUSD' here is only a
            # construction-time placeholder — this instance is a shared
            # singleton reused for every pair. orphan_consumers.py's
            # enrich_market_context() repoints `.symbol` to the actual
            # pair being processed before every analyze() call. Do not
            # rely on this literal for the analyzed symbol.
            _service = _MTFAnalyzer(symbol='EURUSD')  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("mtf_analyzer")(df, ...)`.
            _service = _MTFAnalyzer
        registry.register_instance("mtf_analyzer", _service)
        _wired.append("mtf_analyzer")
        log.info("  ✓ mtf_analyzer")
        _SUBSCRIBED["mtf_analyzer"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("mtf_analyzer", str(_e)))
        log.warning("  ✗ mtf_analyzer: %s", _e)

    # 8-step PA engine w/ S/R + S/D + MTF + session filter
    try:
        from analysis.multi_strategy_pa_engine import MultiStrategyPAEngine as _MultiStrategyPAEngine
        try:
            _service = _MultiStrategyPAEngine()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("multi_strategy_pa_engine")(df, ...)`.
            _service = _MultiStrategyPAEngine
        registry.register_instance("multi_strategy_pa_engine", _service)
        _wired.append("multi_strategy_pa_engine")
        log.info("  ✓ multi_strategy_pa_engine")
        _SUBSCRIBED["multi_strategy_pa_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("multi_strategy_pa_engine", str(_e)))
        log.warning("  ✗ multi_strategy_pa_engine: %s", _e)

    # Day-44 impulse-based order-block detection
    try:
        from analysis.order_block import OrderBlockDetector as _OrderBlockDetector
        try:
            _service = _OrderBlockDetector()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("order_block_detector")(df, ...)`.
            _service = _OrderBlockDetector
        registry.register_instance("order_block_detector", _service)
        _wired.append("order_block_detector")
        log.info("  ✓ order_block_detector")
        _SUBSCRIBED["order_block_detector"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("order_block_detector", str(_e)))
        log.warning("  ✗ order_block_detector: %s", _e)

    # Book P81-95 pin bar with 3 filters + 2 entries
    try:
        from analysis.pin_bar_strategy import PinBarStrategy as _PinBarStrategy
        try:
            _service = _PinBarStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("pin_bar_strategy")(df, ...)`.
            _service = _PinBarStrategy
        registry.register_instance("pin_bar_strategy", _service)
        _wired.append("pin_bar_strategy")
        log.info("  ✓ pin_bar_strategy")
        _SUBSCRIBED["pin_bar_strategy"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("pin_bar_strategy", str(_e)))
        log.warning("  ✗ pin_bar_strategy: %s", _e)

    # Western measured-move targets (module-level fns) (registered as module/class — callers invoke directly)
    try:
        from analysis.price_target_module import box_breakout_target as _box_breakout_target
        registry.register_instance("price_target_module", _box_breakout_target)
        _wired.append("price_target_module")
        log.info("  ✓ price_target_module (as module)")
        _SUBSCRIBED["price_target_module"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("price_target_module", str(_e)))
        log.warning("  ✗ price_target_module: %s", _e)

    # DST-aware London open manipulation detection
    try:
        from analysis.session_analysis import LondonManipulationDetector as _LondonManipulationDetector
        try:
            _service = _LondonManipulationDetector()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("session_analysis")(df, ...)`.
            _service = _LondonManipulationDetector
        registry.register_instance("session_analysis", _service)
        _wired.append("session_analysis")
        log.info("  ✓ session_analysis")
        _SUBSCRIBED["session_analysis"] = "analysis.session.ready"  # empty = no subscription
    except Exception as _e:
        _failed.append(("session_analysis", str(_e)))
        log.warning("  ✗ session_analysis: %s", _e)

    # Zone-based stop-hunt detector + trade-signal generator (class)
    try:
        from analysis.stop_hunt_signal_engine import StopHuntSignalEngine as _StopHuntSignalEngine
        try:
            _service = _StopHuntSignalEngine()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("stop_hunt_signal_engine")(df, ...)`.
            _service = _StopHuntSignalEngine
        registry.register_instance("stop_hunt_signal_engine", _service)
        _wired.append("stop_hunt_signal_engine")
        log.info("  ✓ stop_hunt_signal_engine")
        _SUBSCRIBED["stop_hunt_signal_engine"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("stop_hunt_signal_engine", str(_e)))
        log.warning("  ✗ stop_hunt_signal_engine: %s", _e)

    # Day-64 currency-strength math
    try:
        from analysis.strength_calculator import StrengthCalculator as _StrengthCalculator
        try:
            _service = _StrengthCalculator()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strength_calculator")(df, ...)`.
            _service = _StrengthCalculator
        registry.register_instance("strength_calculator", _service)
        _wired.append("strength_calculator")
        log.info("  ✓ strength_calculator")
        _SUBSCRIBED["strength_calculator"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strength_calculator", str(_e)))
        log.warning("  ✗ strength_calculator: %s", _e)

    # Book P79-80 unifying trend-level framework
    try:
        from analysis.trend_level_signal import TrendLevelSignalFramework as _TrendLevelSignalFramework
        try:
            _service = _TrendLevelSignalFramework(timeframe='H1')  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("trend_level_signal")(df, ...)`.
            _service = _TrendLevelSignalFramework
        registry.register_instance("trend_level_signal", _service)
        _wired.append("trend_level_signal")
        log.info("  ✓ trend_level_signal")
        _SUBSCRIBED["trend_level_signal"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("trend_level_signal", str(_e)))
        log.warning("  ✗ trend_level_signal: %s", _e)

    # SQLite-backed spread+commission+swap+slippage tracker
    try:
        from monitoring.cost_analysis import CostTracker as _CostTracker
        try:
            _service = _CostTracker()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("cost_tracker")(df, ...)`.
            _service = _CostTracker
        registry.register_instance("cost_tracker", _service)
        _wired.append("cost_tracker")
        log.info("  ✓ cost_tracker")
        _SUBSCRIBED["cost_tracker"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("cost_tracker", str(_e)))
        log.warning("  ✗ cost_tracker: %s", _e)

    # Day-91 hotfix: tracks first_blocked_at root cause
    try:
        from monitoring.signal_debugger import get_signal_debugger as _get_signal_debugger
        try:
            _service = _get_signal_debugger()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("signal_debugger")(df, ...)`.
            _service = _get_signal_debugger
        registry.register_instance("signal_debugger", _service)
        _wired.append("signal_debugger")
        log.info("  ✓ signal_debugger")
        _SUBSCRIBED["signal_debugger"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("signal_debugger", str(_e)))
        log.warning("  ✗ signal_debugger: %s", _e)

    # Background health monitor + auto-recovery
    try:
        from system.watchdog import SystemWatchdog as _SystemWatchdog
        try:
            _service = _SystemWatchdog()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("system_watchdog")(df, ...)`.
            _service = _SystemWatchdog
        registry.register_instance("system_watchdog", _service)
        _wired.append("system_watchdog")
        log.info("  ✓ system_watchdog")
        _SUBSCRIBED["system_watchdog"] = "system.watchdog.start"  # empty = no subscription
    except Exception as _e:
        _failed.append(("system_watchdog", str(_e)))
        log.warning("  ✗ system_watchdog: %s", _e)

    # Latency-aware strategy gating (disables scalping when ping > 300ms)
    try:
        from system.network_monitor import NetworkMonitor as _NetworkMonitor
        try:
            _service = _NetworkMonitor()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("network_monitor")(df, ...)`.
            _service = _NetworkMonitor
        registry.register_instance("network_monitor", _service)
        _wired.append("network_monitor")
        log.info("  ✓ network_monitor")
        _SUBSCRIBED["network_monitor"] = "system.network.status"  # empty = no subscription
    except Exception as _e:
        _failed.append(("network_monitor", str(_e)))
        log.warning("  ✗ network_monitor: %s", _e)

    # Institutional-grade breakout (NaN-safe)
    try:
        from strategy.breakout import BreakoutStrategy as _BreakoutStrategy
        try:
            _service = _BreakoutStrategy(config=None)  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_breakout")(df, ...)`.
            _service = _BreakoutStrategy
        registry.register_instance("strategy_breakout", _service)
        _wired.append("strategy_breakout")
        log.info("  ✓ strategy_breakout")
        _SUBSCRIBED["strategy_breakout"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_breakout", str(_e)))
        log.warning("  ✗ strategy_breakout: %s", _e)

    # EMA-200 + RSI-50 institutional rewrite
    try:
        from strategy.ema_rsi_combo import ComboConfig as _ComboConfig
        try:
            _service = _ComboConfig()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_ema_rsi_combo")(df, ...)`.
            _service = _ComboConfig
        registry.register_instance("strategy_ema_rsi_combo", _service)
        _wired.append("strategy_ema_rsi_combo")
        log.info("  ✓ strategy_ema_rsi_combo")
        _SUBSCRIBED["strategy_ema_rsi_combo"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_ema_rsi_combo", str(_e)))
        log.warning("  ✗ strategy_ema_rsi_combo: %s", _e)

    # BB + RSI mean-reversion (ADX-gated to ranging only)
    try:
        from strategy.mean_reversion import MeanReversionConfig as _MeanReversionConfig
        try:
            _service = _MeanReversionConfig()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_mean_reversion")(df, ...)`.
            _service = _MeanReversionConfig
        registry.register_instance("strategy_mean_reversion", _service)
        _wired.append("strategy_mean_reversion")
        log.info("  ✓ strategy_mean_reversion")
        _SUBSCRIBED["strategy_mean_reversion"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_mean_reversion", str(_e)))
        log.warning("  ✗ strategy_mean_reversion: %s", _e)

    # Compact ROC + volume + ADX strategy
    try:
        from strategy.momentum import MomentumStrategy as _MomentumStrategy
        try:
            _service = _MomentumStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_momentum")(df, ...)`.
            _service = _MomentumStrategy
        registry.register_instance("strategy_momentum", _service)
        _wired.append("strategy_momentum")
        log.info("  ✓ strategy_momentum")
        _SUBSCRIBED["strategy_momentum"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_momentum", str(_e)))
        log.warning("  ✗ strategy_momentum: %s", _e)

    # EMA pullback with ADX filter
    try:
        from strategy.pullback import PullbackStrategy as _PullbackStrategy
        try:
            _service = _PullbackStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_pullback")(df, ...)`.
            _service = _PullbackStrategy
        registry.register_instance("strategy_pullback", _service)
        _wired.append("strategy_pullback")
        log.info("  ✓ strategy_pullback")
        _SUBSCRIBED["strategy_pullback"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_pullback", str(_e)))
        log.warning("  ✗ strategy_pullback: %s", _e)

    # Range-bound support/resistance fades
    try:
        from strategy.range_trading import RangeTradingStrategy as _RangeTradingStrategy
        try:
            _service = _RangeTradingStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_range_trading")(df, ...)`.
            _service = _RangeTradingStrategy
        registry.register_instance("strategy_range_trading", _service)
        _wired.append("strategy_range_trading")
        log.info("  ✓ strategy_range_trading")
        _SUBSCRIBED["strategy_range_trading"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_range_trading", str(_e)))
        log.warning("  ✗ strategy_range_trading: %s", _e)

    # Breakout-retest entries
    try:
        from strategy.retest import RetestStrategy as _RetestStrategy
        try:
            _service = _RetestStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_retest")(df, ...)`.
            _service = _RetestStrategy
        registry.register_instance("strategy_retest", _service)
        _wired.append("strategy_retest")
        log.info("  ✓ strategy_retest")
        _SUBSCRIBED["strategy_retest"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_retest", str(_e)))
        log.warning("  ✗ strategy_retest: %s", _e)

    # S/R reversal with candlestick confirmation
    try:
        from strategy.reversal import ReversalStrategy as _ReversalStrategy
        try:
            _service = _ReversalStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_reversal")(df, ...)`.
            _service = _ReversalStrategy
        registry.register_instance("strategy_reversal", _service)
        _wired.append("strategy_reversal")
        log.info("  ✓ strategy_reversal")
        _SUBSCRIBED["strategy_reversal"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_reversal", str(_e)))
        log.warning("  ✗ strategy_reversal: %s", _e)

    # M1/M5/M15 scalping with 8-point checklist
    try:
        from strategy.scalping_strategy import ScalpingStrategy as _ScalpingStrategy
        try:
            _service = _ScalpingStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_scalping")(df, ...)`.
            _service = _ScalpingStrategy
        registry.register_instance("strategy_scalping", _service)
        _wired.append("strategy_scalping")
        log.info("  ✓ strategy_scalping")
        _SUBSCRIBED["strategy_scalping"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_scalping", str(_e)))
        log.warning("  ✗ strategy_scalping: %s", _e)

    # EMA-9/21 + SMA-50/200 + MACD confirmation
    try:
        from strategy.trend_follow import TrendFollowStrategy as _TrendFollowStrategy
        try:
            _service = _TrendFollowStrategy()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("strategy_trend_follow")(df, ...)`.
            _service = _TrendFollowStrategy
        registry.register_instance("strategy_trend_follow", _service)
        _wired.append("strategy_trend_follow")
        log.info("  ✓ strategy_trend_follow")
        _SUBSCRIBED["strategy_trend_follow"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("strategy_trend_follow", str(_e)))
        log.warning("  ✗ strategy_trend_follow: %s", _e)

    # Fixed-format audit block for grep/dashboard parsing
    try:
        from utils.decision_logger import log_decision_block as _log_decision_block
        try:
            _service = _log_decision_block()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("decision_logger")(df, ...)`.
            _service = _log_decision_block
        registry.register_instance("decision_logger", _service)
        _wired.append("decision_logger")
        log.info("  ✓ decision_logger")
        _SUBSCRIBED["decision_logger"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("decision_logger", str(_e)))
        log.warning("  ✗ decision_logger: %s", _e)

    # Atomic JSON I/O with file locking (fcntl/msvcrt)
    try:
        from utils.safe_json import safe_read_json as _safe_read_json
        try:
            _service = _safe_read_json()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("safe_json")(df, ...)`.
            _service = _safe_read_json
        registry.register_instance("safe_json", _service)
        _wired.append("safe_json")
        log.info("  ✓ safe_json")
        _SUBSCRIBED["safe_json"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("safe_json", str(_e)))
        log.warning("  ✗ safe_json: %s", _e)

    # JSON-or-text logging adapter (drop-in)
    try:
        from utils.structured_logger import get_logger as _get_logger
        try:
            _service = _get_logger()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("structured_logger")(df, ...)`.
            _service = _get_logger
        registry.register_instance("structured_logger", _service)
        _wired.append("structured_logger")
        log.info("  ✓ structured_logger")
        _SUBSCRIBED["structured_logger"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("structured_logger", str(_e)))
        log.warning("  ✗ structured_logger: %s", _e)

    # Pip-size resolver (JPY/XAU/XAG/crypto) + dep-installer
    try:
        from utils.pip_utils import pip_size as _pip_size
        try:
            _service = _pip_size()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("pip_utils")(df, ...)`.
            _service = _pip_size
        registry.register_instance("pip_utils", _service)
        _wired.append("pip_utils")
        log.info("  ✓ pip_utils")
        _SUBSCRIBED["pip_utils"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("pip_utils", str(_e)))
        log.warning("  ✗ pip_utils: %s", _e)

    # 28-feature set with cyclical time encoding
    try:
        from features.indicators_v5 import add_indicators as _add_indicators
        try:
            _service = _add_indicators()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("indicators_v5")(df, ...)`.
            _service = _add_indicators
        registry.register_instance("indicators_v5", _service)
        _wired.append("indicators_v5")
        log.info("  ✓ indicators_v5")
        _SUBSCRIBED["indicators_v5"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("indicators_v5", str(_e)))
        log.warning("  ✗ indicators_v5: %s", _e)

    # Lightweight registry for ported MQL5 indicators
    try:
        from intelligence.ported_indicators_registry import register as _register
        try:
            _service = _register()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ported_indicators_registry")(df, ...)`.
            _service = _register
        registry.register_instance("ported_indicators_registry", _service)
        _wired.append("ported_indicators_registry")
        log.info("  ✓ ported_indicators_registry")
        _SUBSCRIBED["ported_indicators_registry"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ported_indicators_registry", str(_e)))
        log.warning("  ✗ ported_indicators_registry: %s", _e)

    # KS test + PSI + ADWIN drift detection
    try:
        from ml.advanced_ml import ConceptDriftDetector as _ConceptDriftDetector
        try:
            _service = _ConceptDriftDetector()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ml_concept_drift_detector")(df, ...)`.
            _service = _ConceptDriftDetector
        registry.register_instance("ml_concept_drift_detector", _service)
        _wired.append("ml_concept_drift_detector")
        log.info("  ✓ ml_concept_drift_detector")
        _SUBSCRIBED["ml_concept_drift_detector"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_concept_drift_detector", str(_e)))
        log.warning("  ✗ ml_concept_drift_detector: %s", _e)

    # Online learning partial_fit
    try:
        from ml.advanced_ml import OnlineLearner as _OnlineLearner
        try:
            _service = _OnlineLearner()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ml_online_learner")(df, ...)`.
            _service = _OnlineLearner
        registry.register_instance("ml_online_learner", _service)
        _wired.append("ml_online_learner")
        log.info("  ✓ ml_online_learner")
        _SUBSCRIBED["ml_online_learner"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_online_learner", str(_e)))
        log.warning("  ✗ ml_online_learner: %s", _e)

    # Predict-with-uncertainty for ML models
    try:
        from ml.advanced_ml import UncertaintyEstimator as _UncertaintyEstimator
        try:
            _service = _UncertaintyEstimator()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ml_uncertainty_estimator")(df, ...)`.
            _service = _UncertaintyEstimator
        registry.register_instance("ml_uncertainty_estimator", _service)
        _wired.append("ml_uncertainty_estimator")
        log.info("  ✓ ml_uncertainty_estimator")
        _SUBSCRIBED["ml_uncertainty_estimator"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_uncertainty_estimator", str(_e)))
        log.warning("  ✗ ml_uncertainty_estimator: %s", _e)

    # Feature-importance + data-sufficiency diagnostics
    try:
        from ml.diagnostic import MLDiagnostic as _MLDiagnostic
        try:
            _service = _MLDiagnostic()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ml_diagnostic")(df, ...)`.
            _service = _MLDiagnostic
        registry.register_instance("ml_diagnostic", _service)
        _wired.append("ml_diagnostic")
        log.info("  ✓ ml_diagnostic")
        _SUBSCRIBED["ml_diagnostic"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_diagnostic", str(_e)))
        log.warning("  ✗ ml_diagnostic: %s", _e)

    # 6-gate feature gatekeeper
    try:
        from ml.validation_framework import ValidationFramework as _ValidationFramework
        try:
            _service = _ValidationFramework()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("ml_validation_framework")(df, ...)`.
            _service = _ValidationFramework
        registry.register_instance("ml_validation_framework", _service)
        _wired.append("ml_validation_framework")
        log.info("  ✓ ml_validation_framework")
        _SUBSCRIBED["ml_validation_framework"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_validation_framework", str(_e)))
        log.warning("  ✗ ml_validation_framework: %s", _e)

    # López de Prado gold-standard labeling (module-level fn) (registered as module/class — callers invoke directly)
    try:
        from ml.triple_barrier_labels import triple_barrier_labels as _triple_barrier_labels
        registry.register_instance("ml_triple_barrier_labels", _triple_barrier_labels)
        _wired.append("ml_triple_barrier_labels")
        log.info("  ✓ ml_triple_barrier_labels (as module)")
        _SUBSCRIBED["ml_triple_barrier_labels"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("ml_triple_barrier_labels", str(_e)))
        log.warning("  ✗ ml_triple_barrier_labels: %s", _e)

    # Time-window trading-session manager (ported from aiomql)
    try:
        from orchestrator.trading_sessions import Sessions as _Sessions
        try:
            _service = _Sessions()  # noqa: E501
        except TypeError:
            # Symbol is a function/dataclass with required args
            # — register the symbol itself so callers invoke it
            # directly: `runtime.get("trading_sessions_manager")(df, ...)`.
            _service = _Sessions
        registry.register_instance("trading_sessions_manager", _service)
        _wired.append("trading_sessions_manager")
        log.info("  ✓ trading_sessions_manager")
        _SUBSCRIBED["trading_sessions_manager"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("trading_sessions_manager", str(_e)))
        log.warning("  ✗ trading_sessions_manager: %s", _e)

    # Pydantic-validated env+.env loader (optional alongside flat config.py) (module-level fn) (registered as module/class — callers invoke directly)
    try:
        from typed_config.loader import load_trading_config as _load_trading_config
        registry.register_instance("typed_config_loader", _load_trading_config)
        _wired.append("typed_config_loader")
        log.info("  ✓ typed_config_loader (as module)")
        _SUBSCRIBED["typed_config_loader"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("typed_config_loader", str(_e)))
        log.warning("  ✗ typed_config_loader: %s", _e)

    # Type-safe frozen config models (Pydantic BaseModel) (registered as module/class — callers invoke directly)
    try:
        from typed_config.schemas import AppConfig as _AppConfig
        registry.register_instance("typed_config_schemas", _AppConfig)
        _wired.append("typed_config_schemas")
        log.info("  ✓ typed_config_schemas (as module)")
        _SUBSCRIBED["typed_config_schemas"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("typed_config_schemas", str(_e)))
        log.warning("  ✗ typed_config_schemas: %s", _e)

    # risk/expectancy.py fixes a genuine bug in analytics/analytics.py:
    # PerformanceAnalyzer.summarize() computes "expectancy" as plain
    # average PnL (total_pnl / total_trades), which is NOT the real
    # expectancy formula (win_rate * avg_win - loss_rate * avg_loss) and
    # can be misleadingly positive/negative vs the true figure. The
    # module already ships a ready-made monkey-patch for exactly this
    # (patch_analytics_expectancy()) but nothing ever called it, so the
    # buggy formula was still live everywhere summarize() is used.
    try:
        from risk.expectancy import patch_analytics_expectancy as _patch_expectancy
        _patch_expectancy()
        _wired.append("expectancy_patch")
        log.info("  ✓ expectancy_patch (PerformanceAnalyzer.summarize() corrected)")
        _SUBSCRIBED["expectancy_patch"] = ""  # empty = no subscription
    except Exception as _e:
        _failed.append(("expectancy_patch", str(_e)))
        log.warning("  ✗ expectancy_patch: %s", _e)


    # ── Post-registration: set up event-bus subscriptions ─────────
    bus = get_bus()
    _subscribed = []
    for service_name, topic in _SUBSCRIBED.items():
        if not topic:
            continue
        try:
            service = registry.get(service_name)
            if service is None:
                continue
            # Subscribe the service's `on_event` method (or `handle`,
            # or `__call__`) — pick the first one that exists.
            handler = getattr(service, "on_event", None) \
                or getattr(service, "handle", None)
            if handler is None and callable(service):
                handler = service
            if handler is None:
                log.debug("    (no handler found for %s; skipping %s subscription)",
                          service_name, topic)
                continue
            bus.subscribe(topic, handler, source=service_name)
            _subscribed.append(service_name)
        except Exception as _e:
            log.debug("    subscription for %s on %s failed: %s",
                      service_name, topic, _e)

    # ── Publish summary event ─────────────────────────────────────
    bus.publish(
        "system.orphan_integration",
        {
            "wired": _wired,
            "failed": [name for name, _ in _failed],
            "subscribed": _subscribed,
            "total_attempted": 83,
        },
        source="orphan_integration",
    )

    log.info("-" * 60)
    log.info("Phase 25 complete — %d/%d wired, %d failed, %d subscribed",
             len(_wired), 83, len(_failed), len(_subscribed))
    if _failed:
        log.warning("Failed modules:")
        for name, err in _failed:
            log.warning("  - %s: %s", name, err[:200])
    log.info("=" * 60)

    # Always ok=True — this phase is additive, not critical.
    return PhaseResult(
        phase=Phase.RUNTIME,  # Use RUNTIME (last in PHASE_ORDER) since
                              # ORPHAN_INTEGRATION isn't in the enum.
        ok=True,
        duration_sec=0.0,
        services_registered=_wired,
    )